blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/reincharts/reincharts/discussions/new?category=general
    about: If you are unsure about something, open a question in our discussion forums.